### ISSUE TITLE
Virus(Windows Defender)

### ISSUE THREAD

**Issue by Olexandr43** [OffsetMods538/MonkeyLib538#1]
Windows Defender says 1.1.0 is Trojan:Script/Wacatac.B!ml 
![image](https://github.com/OffsetMods538/MonkeyLib538/assets/161527365/67c93547-33cb-4aa1-9db0-3017409536b5)

**Comment by OffsetMonkey538** [comment]
Uhh that's interesting

**Comment by OffsetMonkey538** [comment]
Nothing on virustotal seems to have flagged it https://www.virustotal.com/gui/file/02d6118a62db8cf99097cd6274e18b5c6899dbae31b091982337b9f1507cef3f/summary

**Comment by OffsetMonkey538** [comment]
I'm guessi ng that it's just windows giving a false positive? But I don't see what it could detect here

**Comment by OffsetMonkey538** [comment]
Did you download the mod from a safe source like from GitHub or Modrinth?

**Comment by OffsetMonkey538** [comment]
Also I mean thw code is open source so you can look through it if you want

**Comment by OffsetMonkey538** [comment]
Ah yeah, seems like this trojan is a false positive pretty often on windows defender
![Screenshot_2024-04-21-08-40-41-629_com discord](https://github.com/OffsetMods538/MonkeyLib538/assets/71213040/9666f16d-d0a7-450e-a9e5-b4ee76127e28)

**Comment by Olexandr43** [comment]
Okay, thx for answering!)
